### ISSUE TITLE
ERRO NA TELA DE CAD USUÁRIO

### ISSUE THREAD

**Issue by rgualdanineto** [SIGSimple/sigsimple-site#30]
ACHO QUE SEI QUAIS SÃO OS ERROS

Não consegui cadastrar APARECE UM AVISO VERMELHO:
null
Ocorreu um erro ao realizar a operação!

VISUALIZADOR
LÊ PASTA EXTERNA
Marcus Coutinho marcus.coutinho@cptm.sp.gov.br

GERADOR DE INFORMAÇÃO
NÃO VÊ GERENCIADOR DE ARQUIVOS
Marcelo Rogano 
marcelo.rogano@consorcio-se-hx.com.br

José Debatin 
jose.debatin@consorcio-se-hx.com.br

**Comment by filipecoelho** [comment]
problema solucionado
