### ISSUE TITLE
FRESCURINHAS

### ISSUE THREAD

**Issue by rgualdanineto** [SIGSimple/sigsimple-site#36]
BOTÃO PARA TELA CHEIA EM TODAS AS TELAS.

EDIÇÃO COM NEGRITO TIPO DE LETRA ETC.. EM TELAS DE TEXTO DE RELATÓRIO.

UTILIZAR O MICROFONE PARA DITAR TEXTO.

É POSSÍVEL DEFINIR A COR PADRÃO POR CLIENTE?

A FOTO DE CAPA JÁ PODE SER ALTERADA POR CLIENTE?

**Comment by filipecoelho** [comment]
Item 1 será atendido pelo chamado #38
Item 2 será atendido pelo chamado #39
Item 4 e 5 serão atendidos pelo chamado #40
