### ISSUE TITLE
cadastro de situação de contrato

### ISSUE THREAD

**Issue by rgualdanineto** [SIGSimple/sigsimple-site#91]
NAS TELAS AUMENTAR O NÚMERO DE CORES E FAZER UM ESQUEMA MAIS PRÁTICO PARA NÃO REPETIR CORES.
SERIA CONVENIENTE AO LADO DE CADA SITUAÇÃO APARECER A COR, ASSIM SERIA UMA LEGENDA.

LIMPAR DADOS NO CADASTRO DE PROJETO SÓ DEIXAR OS COMUNS A TODAS AS OBRAS. VER A IDEIA PODE TIRAR ESTE PROBLEMA.

**Comment by filipecoelho** [comment]
será atendido pelo chamado #83
